spring.application.name=burnout-prediction-system
spring.datasource.url=jdbc:postgresql://localhost:5435/burnout_system
spring.datasource.username=dev
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#Jira
integration.jira.url=https://se2rgmamaev.atlassian.net
integration.jira.username=1hirokoae@gmail.com
integration.jira.token=ATATT3xFfGF0m2qgUdNFlJmgoBEMyRCAEet5PJ1Oz-E4lswxLlsUE8cBuWRuTlp3R2gj30jCrrJjMoWZEiZKFszjx2GgnsV9PuNfFkmX3H0ioRzQHyu0kIX7Zb4itDnQxaagS0R1HR0Md34GVhm_nBreT4spLar9WHcg5TQ9Q0H-HAQtwj0kTOw=CE6C7C88

#Github
integration.github.repo=https://gitlab.com
integration.github.token=gitlab_token
integration.github.owner=12345