spring.application.name=burnout-prediction-system

spring.datasource.url=jdbc:postgresql://localhost:5435/burnout_system
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Профиль для системы (prod / mock)
spring.profiles.active=${PROFILE}
# JWT Security
app.security.jwt.secret=${JWT_SECRET}
# Ключ шифрования. Берется из ОС, если его нет - используется базовый.
app.security.master-key=${MASTER_KEY}
# Время жизни токена: 15 минут
app.security.jwt.expirationMs=900000
# Соль компании для хеширования
app.security.hash-salt=${HASH_SALT}
# Аутентификация для админа
app.security.admin-login=${ADMIN_LOGIN}
app.security.admin-password=${ADMIN_PASSWORD}
# Аутентификация для HR
app.security.hr-login=${HR_LOGIN}
app.security.hr-password=${HR_PASSWORD}
# Аутентификация для VIEWER
app.security.viewer-login=${VIEWER_LOGIN}
app.security.viewer-password=${VIEWER_PASSWORD}
