spring.application.name=burnout-prediction-system
spring.datasource.url=jdbc:postgresql://localhost:5435/burnout_system
spring.datasource.username=dev
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#Jira
integration.jira.url=https://se2rgmamaev.atlassian.net
integration.jira.username=${JIRA_USERNAME}
integration.jira.token=${JIRA_TOKEN}

#Github
# integration.github.repo=self-destruct-notes
integration.github.token=${GITHUB_TOKEN}
integration.github.owner=MamaevSergey

app.mock-data.enabled=true